
roadside_encounters = [{ 
1: 'A huge nest has fallen from a tree on the side of the road: The strange-looking eggs within seem on the verge of hatching' ,
2: 'A dwarf falls from the sky onto the road with a splat: (Did a creature drop it, was he launched into the air, did he fall from a floating fortress?)',
3: 'A row of severed heads on spikes and a warning sign claiming, “Dis Rode Belong Negan”',
4: 'A very small goblin wearing an old carpet as a cape leaps into the path and demands tribute',
5: 'A crazed halfling, starved out of his mind, jumps to the backs of the PCs and rips their packs apart with his teeth in search of food',
6: 'A bounty hunter tracks his target',
7: 'A lush garden is filled with ripe vegetables: It is protected by a magical ward, but what is triggered when entering the garden?',
8: 'A monstrous mount is ridden by a gnome: Friend or foe?',
9: 'Two guards hold a wanted poster: They carefully studies the party as they pass by',
10: 'A smiling roadside merchant roasts rats, frogs, and squirrels on sticks: He offers a bite to the PCs',
11: 'A chatty bard walks alongside the party: Time for an exposition dump!',
12: 'A bridle ties a well-groomed speckled horse to a nearby tree: The horse is fitted with an elegant but empty saddle: Who does it belong to? Do the PCs take it?',
13: 'A powerful storm forced you to take the only available refuge: an elderly couple\'s home just off the side of the road: The two room home holds numerous open cups of the same pungent liquid',
14: 'A naked bard asks for a lift to the nearest inn where he left his clothes and money',
15: 'Alongside the road, a charlatan asks the party if they want to see a performance of his trained pets: The slightest affirmative answer causes Steve to give a whistle, and a huge swarm of ravenous locusts suddenly manifests',
16: 'A fat friar hurries past the PCs mumbling, “It isn\'t fair:”',
17: 'An evil wizard is tied to a stake, the body still smoking',
18: 'Three young men work on tipping over an occupied outhouse',
19: 'A band of orcs runs toward the party: They look over their shoulders and try to run through the party: Something dreadful has terrified them, and the party is heading in its direction!',
20: 'Traveling off the main road, the PCs feel like they are being followed: Who is hunting them?',
21: 'Three types of meat hang on a spit over a campfire: It is clear that it is three types of humanoids that hang over the flames',
22: 'A snowy road hides a sinkhole that chutes the party on a slalom slide down the mountainside',
23: 'A well-spoken bugbear wearing fine studded leather armor is trapped under a fallen tree: He begs the party to come to his aid',
24: 'A ranger stops by the camp one night and gives them advice on the trail ahead, including places to camp and a tavern where they can get good rates if they mention his name: All his advice is impeccable, but when they mention his name at the tavern, they are told he died years ago on that very road',
25: 'A shopping list for potions lies on the ground',
26: 'The local baron has enacted a toll bridge: Several peasants were unaware, and cannot afford the toll: They beg the PCs for change',
27: 'You find the remains of a pouch that contains coins fro ma land you do not recognize',
28: 'The party hears a long stream of curses further up the road: Then they spot a head in the road: A person is still alive, buried up to his neck!',
29: 'An arrow hits a nearby trunk, a message wrapped around the shaft',
30: 'A bridge is missing: Where it used to be is now a ferry service, for a sizable fee: The ferry looks like it might consist of bridge parts, and only takes a few travelers at a time',
31: 'A loaded wagon travels down the road toward the party, but it has no apparent means of propulsion',
32: 'As bandits attack, the PCs realize a friend of theirs is among the robbers',
33: 'There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed',
34: 'Orcs gather twigs and berries along the road and it is clear they have non-hostile purpose: Will the PCs attack just because they are orcs?',
35: 'A tree falls onto the road: Then a fireball blows up the tree: It appears the PCs are in the middle of a skirmish between druids and fire wizards',
36: 'Flowers by the roadside turn their heads to follow the party, and they are getting larger',
37: 'An overturned beer cart lies in the road: Nearby, an enormous troll snores loudly, surrounded by empty kegs',
38: 'A set of shackles lies at the side of the road',
39: 'A village can be seen to the west: It is not on any of the maps',
40: 'Three pilgrims trudge along the dusty road, an old man and two young men: Simple travelers? Or are they more than they seem?',
41: 'You stumble upon an old scroll case wedged between a tangle of tree branches: Inside is a village\'s charter of rights and freedoms',
42: 'A dead magic user clutches a scroll in his stiff hand: The scroll says something important',
43: 'A single giant footprint lies along the path: There are no other signs of such footprints in the area',
44: 'You party awakens to find all your gear has been stolen during the night: A quick search reveals twelve sets of tracks and, lying in the middle of your campsite, a smoldering pouch of herbs that, when you sniff them, make you feel slightly drowsy',
45: 'An enormous dragon lands on the road in front of the group: It asks for directions to a certain village, gives the party a generous tip, and then flies off saying he intends to raze it to the ground',
46: 'An exotic, almost alien weapon or tool lies on the side of the road',
47: 'The PCs mysteriously repeat a piece of road they already passed, though the route has been perfectly straight to this point: The road even includes their footprints',
48: 'A dozen townsfolk are running after a fleeing woman and attempting to stone her to death for being a prostitute',
49: 'Two other adventuring groups are arguing in the middle of the road',
50: 'You see a man-sized shadow from the left side of the road waving its arms at you: “Over here, quickly, I have caught one!”',
51: 'A person fleeing arranged marriage seeks refuge with the PCs',
52: 'Picked mushrooms lay on stump to dry',
53: 'A strange old man offers the PCs a scroll in a language they cannot read',
54: 'Gnomes are holding a yard sale! They have any number of strange and fascinating contraptions',
55: 'Someone has scattered caltrops across the road',
56: 'You encounter a monk, a monkey, a turtle and a pig, all heading west',
57: 'A weathered sign points off the road, yet with no apparent trail to follow',
58: 'The next 100 feet of road are covered with newly grown grass',
59: 'Ladies clothing and under clothing are strewn in the bushes along the road: How did these get here?',
60: 'A formerly brilliant wizard, now pesters the party with the incoherent rants of a man driven mad by a botched invisibility spell',
61: 'A drunken dwarf staggers along, challenging everyone to a wrestling match',
62: 'A goblin, on fire, runs shrieking past the party',
63: 'A rock with an odd, glowing rune sits by the road ahead',
64: 'A noble, disguised as a filthy beggar, tests the party\'s compassion and generosity: If they pass whatever standard he sets, then he becomes a source of various quests that require personal sacrifice to accomplish',
65: 'A circus is set up alongside the road: A barker on the roadside cajoles you to “come inside and see what wonders it holds”',
66: 'The road crests a hill, and spread out before the group is a stunning, sweeping vista of the land beyond: A painter sits nearby, capturing the scene, and asks the group to pose for his foreground',
67: 'An overturned rowboat sits on the side of the road: There is no river or stream nearby: Under the rowboat is an entrance to a lair',
68: 'A wandering cleric begs the heroes to recover a relic for them',
69: 'A road sign saying where you came from is ahead of you',
70: 'A group of guardsmen hang wanted posters on trees: One face looks familiar to a PC',
71: 'A carriage is stuck high up in a tree',
72: 'In the morning while breaking camp, the PCs spot a bush that was not there before',
73: 'A beautiful woman, adorned in the robes of an enchantress, emerges from hiding near the road and implores you to lend her aid',
74: 'The road is lined with snakes sleeping in the sun',
75: 'A necromancer uses his talents to animate animal and human corpses and forces them to perform in a roadside circus: The townsfolk from a nearby village seem to enjoy the show a bit too much',
76: 'A chain gang digs ditches beside the road',
77: 'A traveling minstrel challenges the wisest looking member of the party to a storytelling contest',
78: 'A wizened tinker sells charms from his cart: dried frogs, finger bones, cat skulls, and the like: Leaving him, you turn to find he is eerily out of sight altogether',
79: 'A paladin of a holy church and his retinue have ridden out on a holy crusade against evil and demand others who serve the cause of good to join their cause on the spot',
80: 'The road starts to get muddy: Soon the mud is two feet deep: Water in the ditches alongside starts to bubble',
81: 'A majestic elk sprints past with something golden caught in its antlers',
82: 'A stranger on the road tells each PC to repent of their sins: He knows details',
83: 'A door stands beside the road, but there is no sign of the rest of the house',
84: 'A wine merchant\'s wagon has shattered a wheel and he offers passers-by cut rate prices on his wares as it is getting repaired',
85: 'An ugly old woman struggles to bring her wash basket of wet clothes up from the creek to the road: She stumbles and drops the laundry back down the slope',
86: 'A monk, collapsed and bleeding on the roadside, pushes an unremarkable ring into a PC\'s hands and desperately whispers, “You must…” before exhaling his last breath',
87: 'A lost gnome asks for directions',
88: 'A dead raven lies on the road, pierced by a bright blue fletched arrow',
89: 'A table on the roadside holds a large basket of fresh vegetables: A sign reads “1 copper a bunch: honesty is a virtue!”',
90: 'You find a small leather bag: It smells of moisture, and contains a set of keys and a vellum map to the location of a small keep',
91: 'The road is littered with bear traps',
92: 'A thick fog has settled on the bridge ahead',
93: 'The group arrives late at night at a tiny village straddling the road: They secure accommodation and food from the friendly locals and fall asleep: In the morning the village is empty and ruined, as if abandoned years ago',
94: 'As the road passes through a hilly region, you spy a cave, from which can be heard the voice of a singing female',
95: 'As you turn the corner, a dwarf and elf are standing over a stack of goblin corpses: They argue over the kill count',
96: 'The party notices a sudden and drastic change in temperature, then just like that, things are back to normal',
97: 'A little girl is watching you from just off the road: The next time you glance over, you see a wolf run away',
98: 'An ecstatic farmer presses a cigar into your hands and proclaims, “It is a girl!”',
99: 'Scratched into the dust of the road are the words, “Good luck tomorrow: You are going to need it:”',
100: 'The entire party suddenly loses their bearings and realize that they have walked the same mile three times: Are they road weary or are they caught in something manipulating them',
}]
